name: model-training
on: [push]
permissions: write-all  #ðŸ’›ì“°ê¸°ê¶Œí•œ ë¶€ì—¬!
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          pip install -r requirements.txt
          python train.py
      - name: Generate Report
        env:
     	      # GITHUB ì»¤ë°‹ ë¡œê·¸ì— ë ˆí¬íŠ¸ë¥¼ ì¶œë ¥í•˜ê¸° ìœ„í•´ GITHUB í† í°ì„ ë„£ì–´ì¤ë‹ˆë‹¤.
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## MODEL METRICS" > report.md
          cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          echo "![](feature_importance.png)" >> report.md
          echo "![](residuals.png)" >> report.md
          cml comment create report.md